# Generated by Django 4.2.2 on 2023-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_services_desription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='summary_text',
        ),
    ]
