# Generated by Django 4.2.2 on 2023-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
            ],
        ),
    ]
