# Generated by Django 4.2.2 on 2023-07-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_remove_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
    ]
