# Generated by Django 4.2.2 on 2023-07-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttext',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
