# Generated by Django 4.2.2 on 2023-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_contacttext_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('short_desc', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
